[versions]
kotlin = "2.0.0"
fabric-loom = "1.6-SNAPSHOT"
iridium = "3.3.1"

#farrow = "1.0.0+arrow.1.2.4"
modmenu = "11.0.0-beta.1"

[libraries]
#farrow = { module = "net.wiredtomato:farrow", version.ref = "farrow" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
iridium = { id = "org.teamvoided.iridium", version.ref = "iridium"}
iridium-publish = { id = "iridium.project.publish-script", version.ref = "iridium"}
iridium-upload = { id = "iridium.mod.upload-script", version.ref = "iridium" }
